<?php

return [
    /*
    Pays 
     */
    'countries' => [
        ['code' => 'AF', 'name' => 'Afghanistan'],
        ['code' => 'ZA', 'name' => 'Afrique du Sud'],
        ['code' => 'AL', 'name' => 'Albanie'],
        ['priority' => '6', 'code' => 'DZ', 'name' => 'Algérie'],
        ['priority' => '7', 'code' => 'DE', 'name' => 'Allemagne'],
        ['code' => 'AD', 'name' => 'Andorre'],
        ['code' => 'AO', 'name' => 'Angola'],
        ['code' => 'SA', 'name' => 'Arabie saoudite'],
        ['code' => 'AR', 'name' => 'Argentine'],
        ['code' => 'AM', 'name' => 'Arménie'],
        ['code' => 'AU', 'name' => 'Australie'],
        ['code' => 'AT', 'name' => 'Autriche'],
        ['code' => 'AZ', 'name' => 'Azerbaïdjan'],
        ['code' => 'BS', 'name' => 'Bahamas'],
        ['code' => 'BH', 'name' => 'Bahreïn'],
        ['code' => 'BD', 'name' => 'Bangladesh'],
        ['code' => 'BB', 'name' => 'Barbade'],
        ['code' => 'BY', 'name' => 'Bélarus'],
        ['priority' => '7', 'code' => 'BE', 'name' => 'Belgique'],
        ['code' => 'BZ', 'name' => 'Belize'],
        ['code' => 'BJ', 'name' => 'Bénin'],
        ['code' => 'BM', 'name' => 'Bermudes'],
        ['code' => 'BT', 'name' => 'Bhoutan'],
        ['code' => 'BO', 'name' => 'Bolivie'],
        ['code' => 'BA', 'name' => 'Bosnie-Herzégovine'],
        ['code' => 'BW', 'name' => 'Botswana'],
        ['code' => 'BR', 'name' => 'Brésil'],
        ['code' => 'BG', 'name' => 'Bulgarie'],
        ['code' => 'BF', 'name' => 'Burkina Faso'],
        ['code' => 'BI', 'name' => 'Burundi'],
        ['code' => 'KH', 'name' => 'Cambodge'],
        ['code' => 'CM', 'name' => 'Cameroun'],
        ['code' => 'CA', 'name' => 'Canada'],
        ['code' => 'CV', 'name' => 'Cap-Vert'],
        ['code' => 'CL', 'name' => 'Chili'],
        ['code' => 'CN', 'name' => 'Chine'],
        ['code' => 'CY', 'name' => 'Chypre'],
        ['code' => 'CO', 'name' => 'Colombie'],
        ['code' => 'CG', 'name' => 'Congo-Brazzaville'],
        ['code' => 'KP', 'name' => 'Corée du Nord'],
        ['code' => 'KR', 'name' => 'Corée du Sud'],
        ['code' => 'CR', 'name' => 'Costa Rica'],
        ['code' => 'CI', 'name' => 'Côte d’Ivoire'],
        ['code' => 'HR', 'name' => 'Croatie'],
        ['code' => 'CU', 'name' => 'Cuba'],
        ['code' => 'DK', 'name' => 'Danemark'],
        ['code' => 'DJ', 'name' => 'Djibouti'],
        ['code' => 'EG', 'name' => 'Égypte'],
        ['code' => 'SV', 'name' => 'El Salvador'],
        ['code' => 'AE', 'name' => 'Émirats arabes unis'],
        ['code' => 'EC', 'name' => 'Équateur'],
        ['priority' => '7', 'code' => 'ES', 'name' => 'Espagne'],
        ['code' => 'EE', 'name' => 'Estonie'],
        ['priority' => '5', 'code' => 'US', 'name' => 'États-Unis'],
        ['code' => 'ET', 'name' => 'Éthiopie'],
        ['code' => 'FJ', 'name' => 'Fidji'],
        ['code' => 'FI', 'name' => 'Finlande'],
        ['priority' => '10', 'code' => 'FR', 'name' => 'France'],
        ['code' => 'GA', 'name' => 'Gabon'],
        ['code' => 'GM', 'name' => 'Gambie'],
        ['code' => 'GH', 'name' => 'Ghana'],
        ['code' => 'GI', 'name' => 'Gibraltar'],
        ['code' => 'GR', 'name' => 'Grèce'],
        ['code' => 'GD', 'name' => 'Grenade'],
        ['priority' => '9', 'code' => 'GP', 'name' => 'Guadeloupe'],
        ['code' => 'GT', 'name' => 'Guatemala'],
        ['code' => 'GG', 'name' => 'Guernesey'],
        ['code' => 'GN', 'name' => 'Guinée'],
        ['code' => 'GQ', 'name' => 'Guinée équatoriale'],
        ['code' => 'GW', 'name' => 'Guinée-Bissau'],
        ['code' => 'GY', 'name' => 'Guyana'],
        ['priority' => '9', 'code' => 'GF', 'name' => 'Guyane française'],
        ['code' => 'HT', 'name' => 'Haïti'],
        ['code' => 'HN', 'name' => 'Honduras'],
        ['code' => 'HU', 'name' => 'Hongrie'],
        ['code' => 'IN', 'name' => 'Inde'],
        ['code' => 'ID', 'name' => 'Indonésie'],
        ['code' => 'IQ', 'name' => 'Irak'],
        ['code' => 'IR', 'name' => 'Iran'],
        ['code' => 'IE', 'name' => 'Irlande'],
        ['code' => 'IS', 'name' => 'Islande'],
        ['code' => 'IL', 'name' => 'Israël'],
        ['priority' => '7', 'code' => 'IT', 'name' => 'Italie'],
        ['code' => 'JM', 'name' => 'Jamaïque'],
        ['code' => 'JP', 'name' => 'Japon'],
        ['code' => 'JE', 'name' => 'Jersey'],
        ['code' => 'JO', 'name' => 'Jordanie'],
        ['code' => 'KZ', 'name' => 'Kazakhstan'],
        ['code' => 'KE', 'name' => 'Kenya'],
        ['code' => 'KW', 'name' => 'Koweït'],
        ['code' => 'LA', 'name' => 'Laos'],
        ['code' => 'LS', 'name' => 'Lesotho'],
        ['code' => 'LV', 'name' => 'Lettonie'],
        ['code' => 'LB', 'name' => 'Liban'],
        ['code' => 'LR', 'name' => 'Libéria'],
        ['code' => 'LY', 'name' => 'Libye'],
        ['code' => 'LI', 'name' => 'Liechtenstein'],
        ['code' => 'LT', 'name' => 'Lituanie'],
        ['priority' => '7', 'code' => 'LU', 'name' => 'Luxembourg'],
        ['code' => 'MK', 'name' => 'Macédoine'],
        ['code' => 'MG', 'name' => 'Madagascar'],
        ['code' => 'MY', 'name' => 'Malaisie'],
        ['code' => 'MW', 'name' => 'Malawi'],
        ['code' => 'MV', 'name' => 'Maldives'],
        ['code' => 'ML', 'name' => 'Mali'],
        ['code' => 'MT', 'name' => 'Malte'],
        ['priority' => '6', 'code' => 'MA', 'name' => 'Maroc'],
        ['priority' => '9', 'code' => 'MQ', 'name' => 'Martinique'],
        ['code' => 'MU', 'name' => 'Maurice'],
        ['code' => 'MR', 'name' => 'Mauritanie'],
        ['code' => 'YT', 'name' => 'Mayotte'],
        ['code' => 'MX', 'name' => 'Mexique'],
        ['code' => 'MD', 'name' => 'Moldavie'],
        ['priority' => '8', 'code' => 'MC', 'name' => 'Monaco'],
        ['code' => 'MN', 'name' => 'Mongolie'],
        ['code' => 'ME', 'name' => 'Monténégro'],
        ['code' => 'MS', 'name' => 'Montserrat'],
        ['code' => 'MZ', 'name' => 'Mozambique'],
        ['code' => 'MM', 'name' => 'Myanmar'],
        ['code' => 'NA', 'name' => 'Namibie'],
        ['code' => 'NP', 'name' => 'Népal'],
        ['code' => 'NI', 'name' => 'Nicaragua'],
        ['code' => 'NE', 'name' => 'Niger'],
        ['code' => 'NG', 'name' => 'Nigéria'],
        ['code' => 'NO', 'name' => 'Norvège'],
        ['code' => 'NC', 'name' => 'Nouvelle-Calédonie'],
        ['code' => 'NZ', 'name' => 'Nouvelle-Zélande'],
        ['code' => 'UG', 'name' => 'Ouganda'],
        ['code' => 'UZ', 'name' => 'Ouzbékistan'],
        ['code' => 'PK', 'name' => 'Pakistan'],
        ['code' => 'PA', 'name' => 'Panama'],
        ['code' => 'PY', 'name' => 'Paraguay'],
        ['priority' => '7', 'code' => 'NL', 'name' => 'Pays-Bas'],
        ['code' => 'PE', 'name' => 'Pérou'],
        ['code' => 'PH', 'name' => 'Philippines'],
        ['code' => 'PL', 'name' => 'Pologne'],
        ['priority' => '9', 'code' => 'PF', 'name' => 'Polynésie française'],
        ['code' => 'PR', 'name' => 'Porto Rico'],
        ['priority' => '7', 'code' => 'PT', 'name' => 'Portugal'],
        ['code' => 'QA', 'name' => 'Qatar'],
        ['code' => 'HK', 'name' => 'R.A.S. chinoise de Hong Kong'],
        ['code' => 'MO', 'name' => 'R.A.S. chinoise de Macao'],
        ['code' => 'CF', 'name' => 'République centrafricaine'],
        ['code' => 'CD', 'name' => 'République démocratique du Congo'],
        ['code' => 'DO', 'name' => 'République dominicaine'],
        ['code' => 'CZ', 'name' => 'République tchèque'],
        ['priority' => '9', 'code' => 'RE', 'name' => 'Réunion'],
        ['code' => 'RO', 'name' => 'Roumanie'],
        ['priority' => '7', 'code' => 'GB', 'name' => 'Royaume-Uni'],
        ['code' => 'RU', 'name' => 'Russie'],
        ['code' => 'RW', 'name' => 'Rwanda'],
        ['code' => 'BL', 'name' => 'Saint-Barthélémy'],
        ['code' => 'KN', 'name' => 'Saint-Kitts-et-Nevis'],
        ['code' => 'SM', 'name' => 'Saint-Marin'],
        ['code' => 'MF', 'name' => 'Saint-Martin'],
        ['code' => 'PM', 'name' => 'Saint-Pierre-et-Miquelon'],
        ['code' => 'VC', 'name' => 'Saint-Vincent-et-les Grenadines'],
        ['code' => 'SH', 'name' => 'Sainte-Hélène'],
        ['code' => 'LC', 'name' => 'Sainte-Lucie'],
        ['code' => 'WS', 'name' => 'Samoa'],
        ['code' => 'SN', 'name' => 'Sénégal'],
        ['code' => 'RS', 'name' => 'Serbie'],
        ['code' => 'CS', 'name' => 'Serbie-et-Monténégro'],
        ['code' => 'SC', 'name' => 'Seychelles'],
        ['code' => 'SL', 'name' => 'Sierra Leone'],
        ['code' => 'SG', 'name' => 'Singapour'],
        ['code' => 'SK', 'name' => 'Slovaquie'],
        ['code' => 'SI', 'name' => 'Slovénie'],
        ['code' => 'SO', 'name' => 'Somalie'],
        ['code' => 'SD', 'name' => 'Soudan'],
        ['code' => 'LK', 'name' => 'Sri Lanka'],
        ['code' => 'SE', 'name' => 'Suède'],
        ['priority' => '7', 'code' => 'CH', 'name' => 'Suisse'],
        ['code' => 'SR', 'name' => 'Suriname'],
        ['code' => 'SY', 'name' => 'Syrie'],
        ['code' => 'TJ', 'name' => 'Tadjikistan'],
        ['code' => 'TW', 'name' => 'Taïwan'],
        ['code' => 'TZ', 'name' => 'Tanzanie'],
        ['code' => 'TD', 'name' => 'Tchad'],
        ['code' => 'PS', 'name' => 'Territoire palestinien'],
        ['code' => 'TH', 'name' => 'Thaïlande'],
        ['code' => 'TG', 'name' => 'Togo'],
        ['code' => 'TO', 'name' => 'Tonga'],
        ['code' => 'TT', 'name' => 'Trinité-et-Tobago'],
        ['code' => 'TA', 'name' => 'Tristan da Cunha'],
        ['priority' => '6', 'code' => 'TN', 'name' => 'Tunisie'],
        ['code' => 'TM', 'name' => 'Turkménistan'],
        ['code' => 'TR', 'name' => 'Turquie'],
        ['code' => 'UA', 'name' => 'Ukraine'],
        ['code' => 'UY', 'name' => 'Uruguay'],
        ['code' => 'VU', 'name' => 'Vanuatu'],
        ['code' => 'VE', 'name' => 'Venezuela'],
        ['code' => 'VN', 'name' => 'Viêt Nam'],
        ['code' => 'WF', 'name' => 'Wallis-et-Futuna'],
        ['code' => 'YE', 'name' => 'Yémen'],
        ['code' => 'ZM', 'name' => 'Zambie'],
        ['code' => 'ZW', 'name' => 'Zimbabwe']
    ],

    'addresses' => [
        [
            'street' => '2 Rue du Soleil',
            'complement1' => '',
            'complement2' => '',
            'postcode' => '34000',
            'city' => 'Montpellier',
            'appartment_number' => '21',
            'country_id' => 58,
        ],
        [
            'street' => '2 Rue du Nuage',
            'complement1' => '',
            'complement2' => '',
            'postcode' => '34640',
            'city' => 'Fabrègue',
            'appartment_number' => '51',
            'country_id' => 58,
        ],
        [
            'street' => '110 Impasse Valteline',
            'complement1' => '',
            'complement2' => '',
            'postcode' => '34000',
            'city' => 'Montpellier',
            'appartment_number' => '301',
            'country_id' => 58,
        ],
        [
            'street' => '15 Rue de Lyon',
            'complement1' => '',
            'complement2' => '',
            'postcode' => '75000',
            'city' => 'Paris',
            'appartment_number' => '41',
            'country_id' => 58,
        ],
        [
            'street' => '2 Rue du General',
            'complement1' => '',
            'complement2' => '',
            'postcode' => '13000',
            'city' => 'Marseille',
            'appartment_number' => '51',
            'country_id' => 58,
        ],
        [
            'street' => '',
            'complement1' => '',
            'complement2' => '',
            'postcode' => '',
            'city' => '',
            'appartment_number' => '',
            'country_id' => 58,
        ],

    ],

    'bedrooms' => [
        [
            'name' => 'Nuit étoilé',
            'phone_bedroom' => '0123456789',
            'price' => '90',
            'image' => '',
            'bedroom_type_id' => 1,
            'hotel_id' => 1,
        ],
        [
            'name' => 'Bon réveil',
            'phone_bedroom' => '9876543210',
            'price' => '120',
            'image' => '',
            'bedroom_type_id' => 2,
            'hotel_id' => 2,
        ], 
        [
            'name' => 'Nuit de rêve',
            'phone_bedroom' => '0123456789',
            'price' => '150',
            'image' => '',
            'bedroom_type_id' => 3,
            'hotel_id' => 2,
        ],
        [
            'name' => 'Nuit de folie',
            'phone_bedroom' => '9876543210',
            'price' => '180',
            'image' => '',
            'bedroom_type_id' => 4,
            'hotel_id' => 2,
        ],
        [
            'name' => 'Voyage dans le temps',
            'phone_bedroom' => '0123456789',
            'price' => '210',
            'image' => '',
            'bedroom_type_id' => 5,
            'hotel_id' => 5,
        ],
        [
            'name' => 'Journée de rêve',
            'phone_bedroom' => '9876543210',
            'price' => '240',
            'image' => '',
            'bedroom_type_id' => 6,
            'hotel_id' => 1,
        ],
        [
            'name' => 'Histoire de famille',
            'phone_bedroom' => '0123456789',
            'price' => '270',
            'image' => '',
            'bedroom_type_id' => 7,
            'hotel_id' => 2,
        ],
        [
            'name' => 'Instant de bonheur',
            'phone_bedroom' => '9876543210',
            'price' => '300',
            'image' => '',
            'bedroom_type_id' => 8,
            'hotel_id' => 1,
        ],
        [
            'name' => 'Odyssée',
            'phone_bedroom' => '0123456789',
            'price' => '330',
            'image' => '',
            'bedroom_type_id' => 7,
            'hotel_id' => 2,
        ],
    ],

    'bedroom_types' => [
        [
            'name' => 'Chambre simple lit.',
            'description' => '',
        ],
        [
            'name' => 'Chambre Double Deluxe.',
            'description' => 'Chambre double Deluxe d\'une superficie de 25 m² est équipée d\'une salle de bains privative.
                Cette chambre double insonorisée dispose de la climatisation et d\'une entrée privée.',
        ], 
        [
            'name' => 'Chambre Double Economique.',
            'description' => 'Située sur le jardin ou sur le canal, au premier étage ou au rez-de chaussée, ces chambres d\'une superficie de 15 m² sont insonorisée et bien équipée : climatisation et ventilateur, bureau, télé à écran plat, connexion WifI, mini bar, coffre fort, grande penderie, ...
                La salle de bain privative dispose d\'un grand lavabo, d\'un sèche cheveux, d\'un distributeur de gel douche/shampoing, d\'une douche dans une baignoire traditionnelle, de WC, bidet, ...',
        ],
        [
            'name' => 'Chambre Double Classique.',
            'description' => 'Chambre double classique d\'une superficie 13 m².
                Cette chambre dispose d\'une salle de bains privative, d\'une télévision à écran LCD, d\'un téléphone et d\'une connexion Wi-Fi gratuite.',
        ],
        [
            'name' => 'Chambre Double Confort.',
            'description' => 'Chambre double confort disposant d\'une salle de bains privative.
                D\'une superficie 13 m², cette chambre double avec vue est insonorisée et dispose d\'une entrée privée.',
        ],
        [
            'name' => 'Chambre lits Jumeaux Classique.',
            'description' => 'Chambre lits Jumeaux Classique d\'une superficie de 13 m².
                Cette chambre dispose d\'une salle de bains privative, d\'une télévision à écran LCD, d\'un téléphone et d\'une connexion Wi-Fi gratuite.',
        ],
        [
            'name' => 'Chambre Triple Economique.',
            'description' => 'Chambre triple Economique, d\'une superficie 13 m², disposant d\'une salle de bains privative.',
        ],
        [
            'name' => 'Chambre Quadruple Familiale.',
            'description' => 'Chambre quadruple familiale d\'une superficie de 15 m².
                Cette chambre dispose d\'une salle de bains privative, d\'une télévision à écran LeCD, d\'un téléphone et d\'une connexion Wi-Fi gratuite.',
        ],
    ],

    'benefits' => [
        [
            'name' => 'Piscine',
            'start_at' => '01/01/22',
            'end_at' => '07/01/22',
            'duration' => '7',
            'image' => '',
            'bedroom_id' => 1,
            'benefit_price_id' => 1,
            'user_id' => 1
        ],
        [
            'name' => 'Petit déjeuné',
            'start_at' => '01/01/22',
            'end_at' => '07/01/22',
            'duration' => '7',
            'image' => '',
            'bedroom_id' => 2,
            'benefit_price_id' => 2,
            'user_id' => 1
        ],  
    ],

    'benefit_prices' => [
        [
            'name' => 'Bain à remous/jacuzzi',
            'description' => '',
            'price' => '100'
        ],
        [
            'name' => 'Sauna',
            'description' => '',
            'price' => '70'
        ],
        [
            'name' => 'Hammam',
            'description' => '',
            'price' => '70'
        ],  
        [
            'name' => 'Spa et centre de bien-être',
            'description' => '',
            'price' => '70'
        ],  
        [
            'name' => 'Spa',
            'description' => '',
            'price' => '70'
        ],  
        [
            'name' => 'Centre de remise en forme',
            'description' => '',
            'price' => '70'
        ],  
        [
            'name' => 'Piscine intérieure',
            'description' => '',
            'price' => '70'
        ],
        [
            'name' => 'Animations en soirée',
            'description' => '',
            'price' => '70'
        ],  
        [
            'name' => ' Plage privée',
            'description' => '',
            'price' => '70'
        ]    
    ],

    'hotels' => [
        [
            'name' => 'Rose étoilé',
            'street' => '87, boulevard de Remy',
            'postcode' => '09458',
            'phone' => '0918951220',
            'image' => '',
            'hotel_class_id' => 1
        ],
        [
            'name' => 'Hotel des Lumières',
            'street' => '3, boulevard de Lacombe',
            'postcode' => '29205',
            'phone' => '0784061486',
            'image' => '',
            'hotel_class_id' => 2
        ],
        [
            'name' => 'La Cabane Dorée',
            'street' => '46, rue Bourgeois',
            'postcode' => '55755',
            'phone' => '0999615884',
            'image' => '',
            'hotel_class_id' => 3
        ], 
        [
            'name' => 'Du Jour au Lendemain',
            'street' => '36, rue de Leveque',
            'postcode' => '90818',
            'phone' => '0145882669',
            'image' => '',
            'hotel_class_id' => 4
        ], 
        [
            'name' => 'Best Western',
            'street' => '5, rue de Herve',
            'postcode' => '24965',
            'phone' => '0375538604',
            'image' => '',
            'hotel_class_id' => 5
        ], 

    ],

    'hotel_classes' => [
        [
            'star_rating' => '*****',
            'description' => '',
        ],
        [
            'star_rating' => '****',
            'description' => '',
        ],   
        [
            'star_rating' => '***',
            'description' => '',
        ],
        [
            'star_rating' => '**',
            'description' => '',
        ],
        [
            'star_rating' => '*',
            'description' => '',
        ]
    ],

    'payments' => [
        [
            'creditCardName' => 'User A',
            'creditCardNumber' => '1234 5678 9876 5432',
            'creditCardExpirationDate' => '01/02/2025',
            'cvv' => '123',
            'start_at' => '01/01/2022',
            'end_at' => '02/01/2022',
            'payment_type_id' => 1,
        ],
        [
            'creditCardName' => 'User B',
            'creditCardNumber' => '9876 5432 3456 7897',
            'creditCardExpirationDate' => '05/05/2027',
            'cvv' => '234',
            'start_at' => '01/01/2022',
            'end_at' => '02/01/2022',
            'payment_type_id' => 2,
        ],
    ],

    'payment_types' => [
        [
            'name' => 'Carte Bleu',
            'code' => 'CB'
        ],
        [
            'name' => 'Master Card',
            'code' => 'MC'
        ],
    ],

    'bookings' => [
        [
            'start_at' => '01/01/22',
            'end_at' => '07/01/22',
            'payment_date' => '01/01/22',
            'amount' => '500',
            'user_id' => 1,
            'payment_id' => 1,
            'bedroom_id' => 1,
        ],
        [
            'start_at' => '07/01/22',
            'end_at' => '10/01/22',
            'payment_date' => '07/01/22',
            'amount' => '200',
            'user_id' => 2,
            'payment_id' => 2,
            'bedroom_id' => 2,
        ],
    ],

    'users' => [
        [
            'lastname' => 'West',
            'firstname' => 'Anna',
            'username' => 'AnnaWest',
            'gender' => 'mme',
            'phone_office' => '+13866833510',
            'phone_mobile' => '+13786364210',
            'position' => '',
            'email' => 'west.anna@example.com',
            'email_verified_at' => '01/01/2022',
            'password' => '6Tu?!9JfqOb',
            'remember_token' => 'osF1CgGFeh',
            'image_path' => '',
            'params' => '{}',
            'preferences' => '{}',
            'role' => 'user',
            'address_id' => 1,
        ],
        [
            'lastname' => 'Dooley',
            'firstname' => 'Xavier',
            'username' => 'Xavier34',
            'gender' => 'mr',
            'phone_office' => '+16547893784',
            'phone_mobile' => '+13879846873',
            'position' => '',
            'email' => 'dooley.xavier@exemple.com',
            'email_verified_at' => '01/01/2022',
            'password' => '6Trehz9ob',
            'remember_token' => 'osF1Cgeja1',
            'image_path' => '',
            'params' => '{}',
            'preferences' => '{}',
            'role' => 'user',
            'address_id' => 2,
        ],
        [
            'lastname' => 'Adèle',
            'firstname' => 'Salmon',
            'username' => 'adèle_salmon',
            'gender' => 'mme',
            'phone_office' => '0516050732',
            'phone_mobile' => '0617236985',
            'position' => '',
            'email' => 'adèle.salmon@exemple.com',
            'email_verified_at' => '01/01/2022',
            'password' => 'ueLw4+T#T_X%jKF>',
            'remember_token' => 'osF1Cgeja1',
            'image_path' => '',
            'params' => '{}',
            'preferences' => '{}',
            'role' => 'user',
            'address_id' => 3,
        ],
        [
            'lastname' => 'Luce-Aurélie ',
            'firstname' => 'Vasseur',
            'username' => 'vasseur69',
            'gender' => 'mme',
            'phone_office' => '0169417208',
            'phone_mobile' => '0165847652',
            'position' => '',
            'email' => 'luce.lucer@exemple.com',
            'email_verified_at' => '01/01/2022',
            'password' => 'KbEWF%`nI',
            'remember_token' => 'osF1Cgeja1',
            'image_path' => '',
            'params' => '{}',
            'preferences' => '{}',
            'role' => 'user',
            'address_id' => 4,
        ],
        [
            'lastname' => 'Étienne',
            'firstname' => 'Ledoux',
            'username' => 'ledoucouc',
            'gender' => 'mr',
            'phone_office' => '0338546982',
            'phone_mobile' => '0614685295',
            'position' => '',
            'email' => 'ledoux.etienne@exemple.com',
            'email_verified_at' => '01/01/2022',
            'password' => '{>@c]ST`QH`',
            'remember_token' => 'osF1Cgeja1',
            'image_path' => '',
            'params' => '{}',
            'preferences' => '{}',
            'role' => 'user',
            'address_id' => 5,
        ],
        [
            'lastname' => 'Super',
            'firstname' => 'Admin',
            'username' => 'superadmin',
            'gender' => 'mr',
            'phone_office' => '',
            'phone_mobile' => '',
            'position' => '1',
            'email' => 'superadmin@admin.com',
            'email_verified_at' => '01/01/2022',
            'password' => 'superadmin',
            'remember_token' => '',
            'image_path' => '',
            'params' => '{}',
            'preferences' => '{}',
            'role' => 'superadmin',
            'address_id' => 6,
        ],
        [
            'lastname' => 'Admin',
            'firstname' => 'Admin',
            'username' => 'admin',
            'gender' => 'mr',
            'phone_office' => '',
            'phone_mobile' => '',
            'position' => '1',
            'email' => 'admin@admin.com',
            'email_verified_at' => '01/01/2022',
            'password' => 'admin',
            'remember_token' => '',
            'image_path' => '',
            'params' => '{}',
            'preferences' => '{}',
            'role' => 'admin',
            'address_id' => 6,
        ],
        [
            'lastname' => 'User',
            'firstname' => 'User',
            'username' => 'user',
            'gender' => 'mr',
            'phone_office' => '',
            'phone_mobile' => '',
            'position' => '1',
            'email' => 'user@exemple.com',
            'email_verified_at' => '01/01/2022',
            'password' => 'useruser',
            'remember_token' => '',
            'image_path' => '',
            'params' => '{}',
            'preferences' => '{}',
            'role' => 'user',
            'address_id' => 6,
        ],
    ],
];





    