<?php

return [
    /*
    Pays 
     */
    'countries' => [
        ['code' => 'AF', 'name' => 'Afghanistan'],
        ['code' => 'ZA', 'name' => 'Afrique du Sud'],
        ['code' => 'AL', 'name' => 'Albanie'],
        ['priority' => '6', 'code' => 'DZ', 'name' => 'Algérie'],
        ['priority' => '7', 'code' => 'DE', 'name' => 'Allemagne'],
        ['code' => 'AD', 'name' => 'Andorre'],
        ['code' => 'AO', 'name' => 'Angola'],
        ['code' => 'SA', 'name' => 'Arabie saoudite'],
        ['code' => 'AR', 'name' => 'Argentine'],
        ['code' => 'AM', 'name' => 'Arménie'],
        ['code' => 'AU', 'name' => 'Australie'],
        ['code' => 'AT', 'name' => 'Autriche'],
        ['code' => 'AZ', 'name' => 'Azerbaïdjan'],
        ['code' => 'BS', 'name' => 'Bahamas'],
        ['code' => 'BH', 'name' => 'Bahreïn'],
        ['code' => 'BD', 'name' => 'Bangladesh'],
        ['code' => 'BB', 'name' => 'Barbade'],
        ['code' => 'BY', 'name' => 'Bélarus'],
        ['priority' => '7', 'code' => 'BE', 'name' => 'Belgique'],
        ['code' => 'BZ', 'name' => 'Belize'],
        ['code' => 'BJ', 'name' => 'Bénin'],
        ['code' => 'BM', 'name' => 'Bermudes'],
        ['code' => 'BT', 'name' => 'Bhoutan'],
        ['code' => 'BO', 'name' => 'Bolivie'],
        ['code' => 'BA', 'name' => 'Bosnie-Herzégovine'],
        ['code' => 'BW', 'name' => 'Botswana'],
        ['code' => 'BR', 'name' => 'Brésil'],
        ['code' => 'BG', 'name' => 'Bulgarie'],
        ['code' => 'BF', 'name' => 'Burkina Faso'],
        ['code' => 'BI', 'name' => 'Burundi'],
        ['code' => 'KH', 'name' => 'Cambodge'],
        ['code' => 'CM', 'name' => 'Cameroun'],
        ['code' => 'CA', 'name' => 'Canada'],
        ['code' => 'CV', 'name' => 'Cap-Vert'],
        ['code' => 'CL', 'name' => 'Chili'],
        ['code' => 'CN', 'name' => 'Chine'],
        ['code' => 'CY', 'name' => 'Chypre'],
        ['code' => 'CO', 'name' => 'Colombie'],
        ['code' => 'CG', 'name' => 'Congo-Brazzaville'],
        ['code' => 'KP', 'name' => 'Corée du Nord'],
        ['code' => 'KR', 'name' => 'Corée du Sud'],
        ['code' => 'CR', 'name' => 'Costa Rica'],
        ['code' => 'CI', 'name' => 'Côte d’Ivoire'],
        ['code' => 'HR', 'name' => 'Croatie'],
        ['code' => 'CU', 'name' => 'Cuba'],
        ['code' => 'DK', 'name' => 'Danemark'],
        ['code' => 'DJ', 'name' => 'Djibouti'],
        ['code' => 'EG', 'name' => 'Égypte'],
        ['code' => 'SV', 'name' => 'El Salvador'],
        ['code' => 'AE', 'name' => 'Émirats arabes unis'],
        ['code' => 'EC', 'name' => 'Équateur'],
        ['priority' => '7', 'code' => 'ES', 'name' => 'Espagne'],
        ['code' => 'EE', 'name' => 'Estonie'],
        ['priority' => '5', 'code' => 'US', 'name' => 'États-Unis'],
        ['code' => 'ET', 'name' => 'Éthiopie'],
        ['code' => 'FJ', 'name' => 'Fidji'],
        ['code' => 'FI', 'name' => 'Finlande'],
        ['priority' => '10', 'code' => 'FR', 'name' => 'France'],
        ['code' => 'GA', 'name' => 'Gabon'],
        ['code' => 'GM', 'name' => 'Gambie'],
        ['code' => 'GH', 'name' => 'Ghana'],
        ['code' => 'GI', 'name' => 'Gibraltar'],
        ['code' => 'GR', 'name' => 'Grèce'],
        ['code' => 'GD', 'name' => 'Grenade'],
        ['priority' => '9', 'code' => 'GP', 'name' => 'Guadeloupe'],
        ['code' => 'GT', 'name' => 'Guatemala'],
        ['code' => 'GG', 'name' => 'Guernesey'],
        ['code' => 'GN', 'name' => 'Guinée'],
        ['code' => 'GQ', 'name' => 'Guinée équatoriale'],
        ['code' => 'GW', 'name' => 'Guinée-Bissau'],
        ['code' => 'GY', 'name' => 'Guyana'],
        ['priority' => '9', 'code' => 'GF', 'name' => 'Guyane française'],
        ['code' => 'HT', 'name' => 'Haïti'],
        ['code' => 'HN', 'name' => 'Honduras'],
        ['code' => 'HU', 'name' => 'Hongrie'],
        ['code' => 'IN', 'name' => 'Inde'],
        ['code' => 'ID', 'name' => 'Indonésie'],
        ['code' => 'IQ', 'name' => 'Irak'],
        ['code' => 'IR', 'name' => 'Iran'],
        ['code' => 'IE', 'name' => 'Irlande'],
        ['code' => 'IS', 'name' => 'Islande'],
        ['code' => 'IL', 'name' => 'Israël'],
        ['priority' => '7', 'code' => 'IT', 'name' => 'Italie'],
        ['code' => 'JM', 'name' => 'Jamaïque'],
        ['code' => 'JP', 'name' => 'Japon'],
        ['code' => 'JE', 'name' => 'Jersey'],
        ['code' => 'JO', 'name' => 'Jordanie'],
        ['code' => 'KZ', 'name' => 'Kazakhstan'],
        ['code' => 'KE', 'name' => 'Kenya'],
        ['code' => 'KW', 'name' => 'Koweït'],
        ['code' => 'LA', 'name' => 'Laos'],
        ['code' => 'LS', 'name' => 'Lesotho'],
        ['code' => 'LV', 'name' => 'Lettonie'],
        ['code' => 'LB', 'name' => 'Liban'],
        ['code' => 'LR', 'name' => 'Libéria'],
        ['code' => 'LY', 'name' => 'Libye'],
        ['code' => 'LI', 'name' => 'Liechtenstein'],
        ['code' => 'LT', 'name' => 'Lituanie'],
        ['priority' => '7', 'code' => 'LU', 'name' => 'Luxembourg'],
        ['code' => 'MK', 'name' => 'Macédoine'],
        ['code' => 'MG', 'name' => 'Madagascar'],
        ['code' => 'MY', 'name' => 'Malaisie'],
        ['code' => 'MW', 'name' => 'Malawi'],
        ['code' => 'MV', 'name' => 'Maldives'],
        ['code' => 'ML', 'name' => 'Mali'],
        ['code' => 'MT', 'name' => 'Malte'],
        ['priority' => '6', 'code' => 'MA', 'name' => 'Maroc'],
        ['priority' => '9', 'code' => 'MQ', 'name' => 'Martinique'],
        ['code' => 'MU', 'name' => 'Maurice'],
        ['code' => 'MR', 'name' => 'Mauritanie'],
        ['code' => 'YT', 'name' => 'Mayotte'],
        ['code' => 'MX', 'name' => 'Mexique'],
        ['code' => 'MD', 'name' => 'Moldavie'],
        ['priority' => '8', 'code' => 'MC', 'name' => 'Monaco'],
        ['code' => 'MN', 'name' => 'Mongolie'],
        ['code' => 'ME', 'name' => 'Monténégro'],
        ['code' => 'MS', 'name' => 'Montserrat'],
        ['code' => 'MZ', 'name' => 'Mozambique'],
        ['code' => 'MM', 'name' => 'Myanmar'],
        ['code' => 'NA', 'name' => 'Namibie'],
        ['code' => 'NP', 'name' => 'Népal'],
        ['code' => 'NI', 'name' => 'Nicaragua'],
        ['code' => 'NE', 'name' => 'Niger'],
        ['code' => 'NG', 'name' => 'Nigéria'],
        ['code' => 'NO', 'name' => 'Norvège'],
        ['code' => 'NC', 'name' => 'Nouvelle-Calédonie'],
        ['code' => 'NZ', 'name' => 'Nouvelle-Zélande'],
        ['code' => 'UG', 'name' => 'Ouganda'],
        ['code' => 'UZ', 'name' => 'Ouzbékistan'],
        ['code' => 'PK', 'name' => 'Pakistan'],
        ['code' => 'PA', 'name' => 'Panama'],
        ['code' => 'PY', 'name' => 'Paraguay'],
        ['priority' => '7', 'code' => 'NL', 'name' => 'Pays-Bas'],
        ['code' => 'PE', 'name' => 'Pérou'],
        ['code' => 'PH', 'name' => 'Philippines'],
        ['code' => 'PL', 'name' => 'Pologne'],
        ['priority' => '9', 'code' => 'PF', 'name' => 'Polynésie française'],
        ['code' => 'PR', 'name' => 'Porto Rico'],
        ['priority' => '7', 'code' => 'PT', 'name' => 'Portugal'],
        ['code' => 'QA', 'name' => 'Qatar'],
        ['code' => 'HK', 'name' => 'R.A.S. chinoise de Hong Kong'],
        ['code' => 'MO', 'name' => 'R.A.S. chinoise de Macao'],
        ['code' => 'CF', 'name' => 'République centrafricaine'],
        ['code' => 'CD', 'name' => 'République démocratique du Congo'],
        ['code' => 'DO', 'name' => 'République dominicaine'],
        ['code' => 'CZ', 'name' => 'République tchèque'],
        ['priority' => '9', 'code' => 'RE', 'name' => 'Réunion'],
        ['code' => 'RO', 'name' => 'Roumanie'],
        ['priority' => '7', 'code' => 'GB', 'name' => 'Royaume-Uni'],
        ['code' => 'RU', 'name' => 'Russie'],
        ['code' => 'RW', 'name' => 'Rwanda'],
        ['code' => 'BL', 'name' => 'Saint-Barthélémy'],
        ['code' => 'KN', 'name' => 'Saint-Kitts-et-Nevis'],
        ['code' => 'SM', 'name' => 'Saint-Marin'],
        ['code' => 'MF', 'name' => 'Saint-Martin'],
        ['code' => 'PM', 'name' => 'Saint-Pierre-et-Miquelon'],
        ['code' => 'VC', 'name' => 'Saint-Vincent-et-les Grenadines'],
        ['code' => 'SH', 'name' => 'Sainte-Hélène'],
        ['code' => 'LC', 'name' => 'Sainte-Lucie'],
        ['code' => 'WS', 'name' => 'Samoa'],
        ['code' => 'SN', 'name' => 'Sénégal'],
        ['code' => 'RS', 'name' => 'Serbie'],
        ['code' => 'CS', 'name' => 'Serbie-et-Monténégro'],
        ['code' => 'SC', 'name' => 'Seychelles'],
        ['code' => 'SL', 'name' => 'Sierra Leone'],
        ['code' => 'SG', 'name' => 'Singapour'],
        ['code' => 'SK', 'name' => 'Slovaquie'],
        ['code' => 'SI', 'name' => 'Slovénie'],
        ['code' => 'SO', 'name' => 'Somalie'],
        ['code' => 'SD', 'name' => 'Soudan'],
        ['code' => 'LK', 'name' => 'Sri Lanka'],
        ['code' => 'SE', 'name' => 'Suède'],
        ['priority' => '7', 'code' => 'CH', 'name' => 'Suisse'],
        ['code' => 'SR', 'name' => 'Suriname'],
        ['code' => 'SY', 'name' => 'Syrie'],
        ['code' => 'TJ', 'name' => 'Tadjikistan'],
        ['code' => 'TW', 'name' => 'Taïwan'],
        ['code' => 'TZ', 'name' => 'Tanzanie'],
        ['code' => 'TD', 'name' => 'Tchad'],
        ['code' => 'PS', 'name' => 'Territoire palestinien'],
        ['code' => 'TH', 'name' => 'Thaïlande'],
        ['code' => 'TG', 'name' => 'Togo'],
        ['code' => 'TO', 'name' => 'Tonga'],
        ['code' => 'TT', 'name' => 'Trinité-et-Tobago'],
        ['code' => 'TA', 'name' => 'Tristan da Cunha'],
        ['priority' => '6', 'code' => 'TN', 'name' => 'Tunisie'],
        ['code' => 'TM', 'name' => 'Turkménistan'],
        ['code' => 'TR', 'name' => 'Turquie'],
        ['code' => 'UA', 'name' => 'Ukraine'],
        ['code' => 'UY', 'name' => 'Uruguay'],
        ['code' => 'VU', 'name' => 'Vanuatu'],
        ['code' => 'VE', 'name' => 'Venezuela'],
        ['code' => 'VN', 'name' => 'Viêt Nam'],
        ['code' => 'WF', 'name' => 'Wallis-et-Futuna'],
        ['code' => 'YE', 'name' => 'Yémen'],
        ['code' => 'ZM', 'name' => 'Zambie'],
        ['code' => 'ZW', 'name' => 'Zimbabwe']
    ],

    'addresses' => [
        [
            'name' => '',
            'street' => '2 Rue du Soleil',
            'complement1' => '',
            'complement2' => '',
            'postcode' => '34000',
            'city' => 'Montpellier',
            'appartment_number' => '21',
            'country_id' => 58,
        ],
        [
            'name' => '',
            'street' => '2 Rue du Nuage',
            'complement1' => '',
            'complement2' => '',
            'postcode' => '34640',
            'city' => 'Fabrègue',
            'appartment_number' => '51',
            'country_id' => 58,
        ],
    ],

    'bedrooms' => [
        [
            'name' => 'Nuit étoilé',
            'phone_bedroom' => '0123456789',
            'price' => '90',
            'image' => '',
            'bedroom_type_id' => 1,
            'hotel_id' => 1,
        ],
        [
            'name' => 'Bon réveil',
            'phone_bedroom' => '9876543210',
            'price' => '120',
            'image' => '',
            'bedroom_type_id' => 2,
            'hotel_id' => 2,
        ],   
    ],

    'bedroom_types' => [
        [
            'name' => 'Chambre simple lit',
            'description' => '',
        ],
        [
            'name' => 'Chambre double lit',
            'description' => '',
        ],   
    ],

    'benefits' => [
        [
            'name' => 'Piscine',
            'start_at' => '01/01/22',
            'end_at' => '07/01/22',
            'duration' => '7',
            'image' => '',
            'bedroom_id' => 1,
            'benefit_price_id' => 1,
            'user_id' => 1
        ],
        [
            'name' => 'Petit déjeuné',
            'start_at' => '01/01/22',
            'end_at' => '07/01/22',
            'duration' => '7',
            'image' => '',
            'bedroom_id' => 2,
            'benefit_price_id' => 2,
            'user_id' => 1
        ],  
    ],

    'benefit_prices' => [
        [
            'name' => 'Prix de la piscine',
            'description' => '',
            'price' => '100'
        ],
        [
            'name' => 'Prix du petit déjeuné',
            'description' => '',
            'price' => '70'
        ],   
    ],

    'hotels' => [
        [
            'name' => 'Rose étoilé',
            'street' => '2 Rue de Lyon',
            'postcode' => '69000',
            'phone' => '123456789',
            'image' => '',
            'hotel_class_id' => 1
        ],
        [
            'name' => 'Hotel des Lumières',
            'street' => '2 Rue du Général',
            'postcode' => '69000',
            'phone' => '123456789',
            'image' => '',
            'hotel_class_id' => 2
        ],   
    ],

    'hotel_classes' => [
        [
            'star_rating' => '*****',
            'description' => '',
        ],
        [
            'star_rating' => '***',
            'description' => '',
        ],   
    ],

    'payments' => [
        [
            'creditCardName' => 'User A',
            'creditCardNumber' => '1234 5678 9876 5432',
            'creditCardExpirationDate' => '01/02/2025',
            'cvv' => '123',
            'start_at' => '01/01/2022',
            'end_at' => '02/01/2022',
            'payment_type_id' => 1,
        ],
        [
            'creditCardName' => 'User B',
            'creditCardNumber' => '9876 5432 3456 7897',
            'creditCardExpirationDate' => '05/05/2027',
            'cvv' => '234',
            'start_at' => '01/01/2022',
            'end_at' => '02/01/2022',
            'payment_type_id' => 2,
        ],
    ],

    'payment_types' => [
        [
            'name' => 'Carte Bleu',
            'code' => 'CB'
        ],
        [
            'name' => 'Master Card',
            'code' => 'MC'
        ],
    ],

    'bookings' => [
        [
            'start_at' => '01/01/22',
            'end_at' => '07/01/22',
            'payment_date' => '01/01/22',
            'amount' => '500',
            'user_id' => 1,
            'payment_id' => 1,
        ],
        [
            'start_at' => '07/01/22',
            'end_at' => '10/01/22',
            'payment_date' => '07/01/22',
            'amount' => '200',
            'user_id' => 2,
            'payment_id' => 2,
        ],
    ],

    'users' => [
        [
            'lastname' => 'West',
            'firstname' => 'Anna',
            'username' => 'AnnaWest',
            'gender' => 'mme',
            'phone_office' => '+13866833510',
            'phone_mobile' => '+13786364210',
            'position' => '',
            'email' => 'west.anna@example.com',
            'email_verified_at' => '01/01/2022',
            'password' => '6Tu?!9JfqOb',
            'remember_token' => 'osF1CgGFeh',
            'image_path' => '',
            'params' => '{}',
            'preferences' => '{}',
            'is_admin' => false,
            'address_id' => 1,
        ],
        [
            'lastname' => 'Dooley',
            'firstname' => 'Xavier',
            'username' => 'Xavier34',
            'gender' => 'mr',
            'phone_office' => '+16547893784',
            'phone_mobile' => '+13879846873',
            'position' => '',
            'email' => 'dooley.xavier@exemple.com',
            'email_verified_at' => '01/01/2022',
            'password' => '6Trehz9ob',
            'remember_token' => 'osF1Cgeja1',
            'image_path' => '',
            'params' => '{}',
            'preferences' => '{}',
            'is_admin' => false,
            'address_id' => 2,
        ],
    ],
];





    